### ISSUE TITLE
Colab usage

### ISSUE THREAD

**Issue by deepika2502** [AliaksandrSiarohin/first-order-model#173]
I do not have a gpu and i use a linux system. So i have to use colab. In that case how do i train the model on colab with my videos and image dataset?

**Comment by AliaksandrSiarohin** [comment]
This would be problematic since colab restart an environment frequently (each 24 hours). First you have to install pytorch==1.00. Clone the repo. Then put your data to colab into data folder. Run the the training with '!python run.py...'. Then you should download your checkpoint before the env restarts, and restart from the checkpoint.

**Comment by deepika2502** [comment]
okay, thank you
