### ISSUE TITLE
how to gen pairs_list file

### ISSUE THREAD

**Issue by dayu1979** [AliaksandrSiarohin/first-order-model#19]
thank you,I want to train model on vox dataset,but some mp4 file seems broken link when I dowload using loadvideo.py , and I dont know how to generate pairs_list file.

**Comment by AliaksandrSiarohin** [comment]
Hi thank you for your interest. Pair list is not needed for training. It is used if you want to animate some specific pairs in animation.py. 

Some links may be broken, because some video in YouTube no longer avaliable. If there are too many links broken, then it may be a YouTube-dl problem. You can try to access broken link videos from browser in order to check. 

Also if you need exactly the same dataset, as I used in the paper, for educational purposes, contact me by email.

**Comment by dayu1979** [comment]
Thanks for your quick reply, I actually want to train with my own datasets.
