### ISSUE TITLE
Error on demo.py.

### ISSUE THREAD

**Issue by kashi211** [AliaksandrSiarohin/first-order-model#4]
Traceback (most recent call last):
  File "demo.py", line 94, in <module>
    predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale)
  File "demo.py", line 61, in make_animation
    use_relative_jacobian=relative, adapt_movement_scale=adapt_movement_scale)
  File "/home/chimpinchief/first-order-model/animate.py", line 33, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: tensor should be 2 dimensional

**Comment by kashi211** [comment]
command i used is:
python3 demo.py  --config config/fashion-256.yaml --driving_video '11.mp4'  --source_image '22.png'  --checkpoint 'fashion.pth.tar'  --relative --adapt_scale

**Comment by AliaksandrSiarohin** [comment]
Most likely you have wrong version of pytorch. You need torch==1.0.0

**Comment by yj7082126** [comment]
Hi. @AliaksandrSiarohin would you mind explaining this "bilinear warping" issue that occurs after pytorch 1.0.0 in detail? And in which part of the code does this issue occurs?

**Comment by AliaksandrSiarohin** [comment]
Hi,
The problem occurs only in training, at some point model start to diverge and produce some bad  solutions. I've tried it with pytroch 1.1, maybe in later versions 1.3, 1.4 it does not occur.
Through I don't have time to investigate it deeply, I belive that the problem is in bilinear warping (https://github.com/AliaksandrSiarohin/first-order-model/blob/720bdd8728c501d88d9fa5731a49a7714547298f/modules/generator.py#L57).
Also, at a test time there are no problems.

**Comment by yj7082126** [comment]
Thank you for your answer, @AliaksandrSiarohin . I tested this issue with versions 1.2, 1.3 and 1.4, and they all ended in vanishing gradients, but version 1.0.1 works. So I believe that some code change between 1.0.1 and 1.1 was the problem, yet on the update notes there wasn't a significant change on torch.nn.functional.

**Comment by AliaksandrSiarohin** [comment]
Dear @yj7082126 thank you for letting me know, 
The reason, I believe it is in grid_sample because in my other project I meet the same problem when I add a grid_sample with PyTorch 1.1. Without it everything was fine.
I'm not familiar with a PyTorch code base, so it is hard to for me to understand what really changed.
Maybe when I have more time, I will try to remove this grid_sample and try different modes of it. 
Anyway thank you for your investigation and for letting me know.

**Comment by yj7082126** [comment]
Thanks!
