### ISSUE TITLE
Can not got any video when crop

### ISSUE THREAD

**Issue by lucasjinreal** [AliaksandrSiarohin/first-order-model#84]
I got command like:

```
ffmpeg -i /media/massive/permanent/datasets/public/videos/trump1.mp4 -ss 4.366666666666666 -t 18.366666666666667 -filter:v "crop=329:329:444:52, scale=256:256" crop.mp4
ffmpeg -i /media/massive/permanent/datasets/public/videos/trump1.mp4 -ss 25.3 -t 30.966666666666665 -filter:v "crop=384:384:417:72, scale=256:256" crop.mp4
ffmpeg -i /media/massive/permanent/datasets/public/videos/trump1.mp4 -ss 70.1 -t 15.800000000000011 -filter:v "crop=312:312:456:62, scale=256:256" crop.mp4
ffmpeg -i /media/massive/permanent/datasets/public/videos/trump1.mp4 -ss 90.83333333333333 -t 9.433333333333337 -filter:v "crop=341:341:461:53, scale=256:256" crop.mp4
ffmpeg -i /media/jintian/massive/permanent/datasets/public/videos/trump1.mp4 -ss 106.33333333333333 -t 7.300000000000011 -filter:v "crop=319:319:472:73, scale=256:256" crop.mp4

```

 But there are no such crop.mp4 generate. what's going on?

**Comment by ArashHosseini** [comment]
@jinfagang short question, are you also calling this command?

**Comment by ghost** [comment]
I had the same problem as you said.

**Comment by ArashHosseini** [comment]
You have to call this command manually, crop_video.py is giving you only the ffmpeg command and you have to call it by your self.

**Comment by ghost** [comment]
@ArashHosseini Thank you very much!!

**Comment by Jessicall** [comment]
@geraltsnake @ArashHosseini 
Hi,what's your command to crop all videos at the same time?
(animation1) root@6ffc0be116fa:/remote-home/my/pycharmprojects/first-order-model# python crop-video.py --inp /remote-home/my/pycharmprojects/first-order-model/data/fashion-dataset/train
Is that right?
And i get the error
File "crop-video.py", line 71
    return f'ffmpeg -i {inp} -ss {start} -t {time} -filter:v "crop={w}:{h}:{left}:{top},scale=256:256" crop.mp4'
                                                                                                               ^
SyntaxError: invalid syntax

**Comment by ArashHosseini** [comment]
@Jessicall i guess that error coming from
Python version, replace the line with 

`return 'ffmpeg -i {inp} -ss {start} -t {time} -filter:v "crop={w}:{h}:{left}:{top},scale=256:256" crop.mp4'.format(inp=inp, start=start, time=time, w=w,h=h,left=left,top=top)`

There is own section about dataset processing, please follow the hints in the README

**Comment by Jessicall** [comment]
Thanks.that problem is solved! @ArashHosseini 

And then i get the error when i run the following command.
(animation1) root@6ffc0be116fa:/remote-home/my/pycharmprojects/first-order-model# python crop-video.py --inp /remote-home/my/pycharmprojects/first-order-model/data/fashion-dataset/train/81FyMPk-WIS.mp4

/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/dask/config.py:129: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/usr/local/miniconda3/envs/animation1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda3/envs/animation1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
0it [00:00, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument

Traceback (most recent call last):
  File "crop-video.py", line 150, in <module>
    commands = process_video(args)
  File "crop-video.py", line 94, in process_video
    bboxes = extract_bbox(frame, fa)
  File "crop-video.py", line 24, in extract_bbox
    bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/face_alignment-1.0.1-py3.5.egg/face_alignment/detection/sfd/sfd_detector.py", line 34, in detect_from_image
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/face_alignment-1.0.1-py3.5.egg/face_alignment/detection/sfd/detect.py", line 30, in detect
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/face_alignment-1.0.1-py3.5.egg/face_alignment/detection/sfd/net_s3fd.py", line 71, in forward
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:

**Comment by Jessicall** [comment]
I follow the hints in the README to do the data processing,but i also encounter the above errors
