### ISSUE TITLE
Advice on training this to master face direction

### ISSUE THREAD

**Issue by simplyexperimental** [AliaksandrSiarohin/first-order-model#87]
Hi there I am new to training and after achieving some good result with the demo I can make the AI do well as long as the picture face does not rotate much. I would like for this AI to master the ability to look from left to middle to right flawlessly while talking.

Would your advice be to grab a couple videos of people doing this behavior and have the AI train on those and then try to evaluate the demo now that the AI is better trained data?

To perfect animating a human face and mouth movements in multiple directions even turning head so we see back of head what would be your general advice on going about that?

Also I have only done tests on a 256 image but i did do on videos 512x512, 640x640 and 256x256 no issues-but the biggest factor ai seems to need is the same zoom between the person of the driving video and the image-if I am not perfectly zoomed on the head in both sources the AI won't animate the mouth any advice on that?

*Update in my testing driving_video size matching the image size from 256x256 on both to 512x512 on both with even some off values like 640x640 for the driving_video and 256x256 on the image-regardless of the dimensions used and whether they match or not the resulting generated video will always look the same-the only factor as mentioned is the zoom factor of the faces from the driving_video and the source image-the more they match in the first frame where they look and their closeness to the camera the more better the AI gets it right. The person can look around after the first few frames but the AI will need to be trained on looking around data. If it can look around convincingly while holding it's shape and talking then this is some next level stuff!

**Comment by AliaksandrSiarohin** [comment]
there I am new to training and after achieving some good result with the demo I can make the AI do well as long as the picture face does not rotate much. I would like for this AI to master the ability to look from left to middle to right flawlessly while talking.

* This likely happens because of not proper alignment between source and first frame of driving. Also large parts need to be Inpainted this is also a problem.

Would your advice be to grab a couple videos of people doing this behavior and have the AI train on those and then try to evaluate the demo now that the AI is better trained data?

* It will only improve inpainting part. For alignment you should invent something different.

To perfect animating a human face and mouth movements in multiple directions even turning head so we see back of head what would be your general advice on going about that?

* Colect more data. Add keypoint supervision. Reduce amount of inpainting needed.

I was not able to understand the rest.
